### ISSUE TITLE
always_hash_content=False not respected for Receiver

### ISSUE THREAD

**Issue by jcwilson** [kumar303/mohawk#2]
The Receiver constructor should accept, extract and pass along *always_hash_content* to the internal Resource constructor, shouldn't it? If it did, we wouldn't need the GET request hack of specifying *content*="" and *content_type*="" at both the Receiver and Sender ends. I think this will also engender a minor change to the behavior of *accept_untrusted_content* since it doesn't seem to handle empty *content/content_type* requests very well.

Just my two cents :)

**Comment by kumar303** [comment]
Feel free to re-open if you can show a traceback.

One thing that might be confusing is that ``accept_untrusted_content = True`` has no effect if the sender specifically included a ``hash``. I think I did this because that's how the Node lib chooses to send an unhashed request (it doesn't specify a hash at all). When the hash is present it seems like it's wrong to ignore the hash. By saying "allow untrusted content" it's really saying allow a request that does not have a content hash but still continue to disallow mis-matching hashes if one is present.
