### ISSUE TITLE
Requests with missing body or content type cause an unexpected ValueError

### ISSUE THREAD

**Issue by edmorley** [kumar303/mohawk#24]
**STR:**
Using something like this with web.py:

``` python
    try:
        Receiver(lookup_hawk_credentials,
                 auth_header,
                 url,
                 env.get('REQUEST_METHOD'),
                 content=web.data(),
                 content_type=env.get('CONTENT_TYPE'))
    except HawkFail as e:
        ...
        raise web.Forbidden()
```

...attempt to POST to the API using httpie and requests-hawk:
`http POST localhost:8080/api/saveclassification --auth-type=hawk --auth='treeherder:zz'`

**Expected:**
Either the request succeeds, or `Receiver` raises one of the `HawkFail` class of exceptions, such that `web.Forbidden()` is raised, resulting in an HTTP 403.

**Actual:**

```
HTTP/1.1 500 Internal Server Error
Content-Type: text/html
Date: Wed, 03 Feb 2016 18:27:06 GMT
Server: localhost
Transfer-Encoding: chunked

internal server error
```

And in the server logs:

```
Traceback (most recent call last):
  ...
  File "/home/Ed/src/orangefactor/server/handlers.py", line 504, in ensure_authenticated
    content_type=env.get('CONTENT_TYPE'))
  File "/home/Ed/.virtualenvs/of/lib/python2.7/site-packages/mohawk/receiver.py", line 111, in __init__
    **auth_kw)
  File "/home/Ed/.virtualenvs/of/lib/python2.7/site-packages/mohawk/base.py", line 42, in _authorize
    content_hash = resource.gen_content_hash()
  File "/home/Ed/.virtualenvs/of/lib/python2.7/site-packages/mohawk/base.py", line 203, in gen_content_hash
    'payload content and/or content_type cannot be '
ValueError: payload content and/or content_type cannot be empty without an explicit allowance

127.0.0.1:50832 - - [03/Feb/2016 18:27:06] "HTTP/1.1 POST /api/saveclassification" - 500 Internal Server Error
```

I follow the motivation for trying to be strict about making people validate the content, however:
(a) I'm not sure it's a correct assumption that `None` values means the developer has instantiated `Receiver` incorrectly. I would have thought it's more likely that the request just didn't contain a body or content type to start with.
(b) It would be more consistent to raise a `HawkFail` (or subclass), since it's non-obvious that I should be catching `ValueError` too.

(Using mohawk 0.3.1 with requests-hawk 1.0.0 and httpie 0.9.3 on Python 2.7.11)

**Comment by kumar303** [comment]
I agree about raising a HawkFail derivative rather than ValueError. That seems like a bug.

The problem you are running into is a problem of detecting the default configuration of `Receiver()`. By default, `Receiver()` is configured with `content=None` so it can't tell the difference when you pass it a `None` content from the user agent.

It could be fixed in a couple ways:

- You could modify your code to send an empty string when the content is None. I'm not positive that this will work but maybe.
- The default invocation of `Receiver()` could be changed to `content=EmptyValue` where `EmptyValue` is a custom class that can be used for comparisons.

**Comment by edmorley** [comment]
> The default invocation of Receiver() could be changed to content=EmptyValue where EmptyValue is a custom class that can be used for comparisons.

Yeah this seems like the best approach.

**Comment by edmorley** [comment]
I have a fix working locally for this, however the additional tests I've added are failing, in part due to #15. I'll see if I can fix that first.

**Comment by edmorley** [comment]
These checks are to basically make the optional `content` and `content_type` parameters mandatory unless the caller has also passed `always_hash_content`.

However that parameter is only used on the sender's side (if we count the receiver's response as sending too); on the other side we don't use the `always_hash_content` parameter, instead there is `accept_untrusted_content`. However at the moment there is no equivalent verification that the `content` and `content_type` have been specified for it.

Should there be?

**Comment by kumar303** [comment]
The sender can say `accept_untrusted_content=False` (which is the default) if it wants to check the signature of the response it gets from the server. Yes, there is a check for this; it is buried in [sender.accept_response()](https://github.com/kumar303/mohawk/blob/master/mohawk/sender.py#L164-L174).

**Comment by edmorley** [comment]
> Yes, there is a check for this; it is buried in sender.accept_response().

I meant a check as to whether `content` and `content_type` were explicitly set to `None` rather than the developer forgetting to pass them in. Such a check doesn't appear to exist for the receiver case at the moment - and if we did want one, it would affect the way I refactor to fix this issue :-)

**Comment by kumar303** [comment]
`None` is the only way mohawk currently checks if the caller (of either a sender or a receiver) has declared `content` or `content_type`. If the value is `None`, mohawk thinks the caller has not declared a value.

**Comment by torotil** [comment]
@kumar303: It might be obvious but … If content and content_type are mandatory, why not make them mandatory parameters for the __init__ function?

**Comment by kumar303** [comment]
They are not mandatory. They do not need to be specified for GET requests (IIRC).

**Comment by torotil** [comment]
If they were not mandatory then this …

> If the value is `None`, mohawk thinks the caller has not declared a value.

would not be an issue at all.

**Comment by kumar303** [comment]
What I meant in https://github.com/kumar303/mohawk/issues/24#issuecomment-179517062 is that I think the intention of :
````python
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'),
         content=web.data(),
         content_type=env.get('CONTENT_TYPE'))
````
was to send empty content:
````python

Receiver(...,
         content='',
         content_type='')
````
which was misunderstood by mohawk as this since the values were `None`:
````python
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'))
````
In other words, mohawk thought that the caller forgot to pass in `content` and `content_type` which could have been a typo in the code.

We could fix it in the ways I proposed.

**Comment by torotil** [comment]
My point was: If all you want is that users of the API can't create a Receiver object without explicitly a `content` and a `content_type` then it might be an option to declare it like this:

```python
class Receiver:
    def __init__(self, content, content_type, …):
        …
```

It's true that this would need a change in how the constructor handles it's arguments - but it is by far the most obvious way …

**Comment by kumar303** [comment]
Well, then you'd have to call it like this when you want to skip content checks:
````python
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'),
         accept_untrusted_content=True,
         content=None
         content_type=None)
````
which seems unnecessarily verbose to me. Currently you can do it like:
````python
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'),
         accept_untrusted_content=True)
````

**Comment by torotil** [comment]
We could drop the `accept_untrusted_content` argument in this case though as it would be redundant as you pointed out. If you want the content validated you pass it - otherwise you pass None. That's also close to how the nodejs implementation works:

1. Pass content and content_type -> content hash is validated.
2. Pass both as none -> skip content hash validation.
3. Forget to pass at least one of them -> get an error.

From this point on we are definitely in the area of personal taste - and in that case I defer to yours as a maintainer. ;)

**Comment by torotil** [comment]
This is what it would look like: https://github.com/torotil/mohawk/commit/b95039d328267a58d9e7859f079b8698b4e59a19

**Comment by kumar303** [comment]
> We could drop the accept_untrusted_content argument in this case though. It would be redundant as you pointed out. If you want the content validated you pass it - otherwise you pass None. 

This is exactly what I want to avoid as it is very easy to pass None without meaning to. In fact, this is a mistake that I explicitly want to avoid:
````python
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'),
         content=web.data(),
         ...)
````

^ the intent here was *not* to accept untrusted content yet your proposal would cause their Hawk verifier to accept any content (when `web.data()` is None) and that opens up several attack vectors. I want the caller to make an explicit choice to skip content checks.

> That's also closer to how the nodejs implementation works:

I know, that's why I created a new interface in mohawk :) I think the nodejs implementation forces the caller to make too many security decisions that require having a deep understanding of how the Hawk protocol works. Mohawk users do not have this burden placed on them. Out of the box, mohawk verifies Hawk requests in the most secure way possible. If you want to be more flexible on security, you have to configure it explicitly.

> From this point on we are definitely in the area of personal taste - and in that case I defer to yours as a maintainer. ;)

Thanks for all the detailed responses. I understand your proposal better now and, yes, I would like to keep the existing mohawk interface for better security.

I will keep this issue open as the original report addresses some things that can be improved.

**Comment by torotil** [comment]
> ^ the intent here was not to accept untrusted content yet your proposal would cause their Hawk verifier to accept any content (when web.data() is None) and that opens up several attack vectors. I want the caller to make an explicit choice to skip content checks.

My code additionally requires that `content_type` is None. Also at least flask returns an empty string `''` instead of `None` if there is no `content`.

But I understand your decision :) Thanks for discussing it!

**Comment by torotil** [comment]
And another consideration: Lets suppose an attacker can make the `content` and `content_type` equal `None` (although they were not `None` in the original request). The only thing he/she could do would be to erase the `content` from the message. Now there is two possibilities:

1. The message contains a (MAC signed) content hash: Then we could check whether the original content was empty (which my patch doesn't).
2. The message doesn't contain a content hash which either means the original content was empty or the Sender did not hash it.

**Comment by torotil** [comment]
After re-reading the thread I have another input. I think there was a mis-understanding / small mistake in [this comment](https://github.com/kumar303/mohawk/issues/24#issuecomment-194493798). My proposal in terms of calls to `mohawk.Receiver` is:

1. Validation of content_hash
```
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'),
         content=content
         content_type=content_type)
```
2. Explicitly not checking the content hash:
```
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'),
         content=None
         content_type=None)
```
This is the one you deemed as too verbose, maybe because you've mistakenly had the `accept_untrusted_content` flag in there.
3. Forgetting to pass the content and content_type parameters:
```
Receiver(lookup_hawk_credentials,
         auth_header,
         url,
         env.get('REQUEST_METHOD'))
# TypeError: … missing required positional argument …
```

I hope this might changes your mind.
